In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3])

In [4]:
arr

array([1, 2, 3])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr

array([1, 2, 3])

In [7]:
arr.size # No of elements in the numpy array

3

In [8]:
arr.shape # Which returns the no of rows and columns

(3,)

In [10]:
arr.ndim # No of dimensions of array

1

In [25]:
arr.dtype # Data type of numpy array elements

dtype('int32')

In [12]:
arr1=np.array([1.2,3,4])

In [13]:
arr1

array([1.2, 3. , 4. ])

In [14]:
arr1.dtype

dtype('float64')

In [21]:
arr1=np.array(["Hello","Hi",1])

In [22]:
arr1

array(['Hello', 'Hi', '1'], dtype='<U5')

In [23]:
arr1.dtype

dtype('<U5')

In [24]:
arr.itemsize # Size of each element in array

4

In [26]:
arr1=np.array([1.2,3,4])

In [27]:
arr1.itemsize

8

In [28]:
arr.max() # Maximum value in array

3

In [29]:
arr.min()# Minimum value in array

1

# 2D Array

In [34]:
arr2=np.array([[1,2,3,4],[5,6,7,8],[5,6,7,9]])

In [36]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 9]])

In [37]:
arr2.ndim

2

In [38]:
arr2.shape

(3, 4)

In [39]:
arr2.size

12

# Array Slicing

In [63]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 9]])

In [62]:
arr2[:,0]

array([1, 5, 5])

In [49]:
arr2[0]

array([1, 2, 3, 4])

In [50]:
arr2[0][0:2]

array([1, 2])

In [53]:
arr2[0,0:2]# array[rows,col]

array([1, 2])

In [54]:
arr2[1,2:4]

array([7, 8])

In [60]:
arr2[0:3,0]

array([1, 5, 5])

In [65]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 9]])

In [72]:
arr2[0,1],arr2[2,3]

(2, 9)

# 3D array

In [56]:
arr3=np.array([[[1,2,3,4],[12,23,33,43]],[[13,2,33,43],[31,23,33,43]]])

In [57]:
arr3

array([[[ 1,  2,  3,  4],
        [12, 23, 33, 43]],

       [[13,  2, 33, 43],
        [31, 23, 33, 43]]])

In [58]:
arr3.shape#3d,2d,1d

(2, 2, 4)

In [29]:
arr3.ndim

3

In [22]:
arr3[1][1][0:2]

array([31, 23])

In [12]:
arr3[1,1,2:4]

array([33, 43])

In [34]:
arr4=np.array([[[[1,2,3,4],[12,23,33,43]],[[13,2,33,43],[31,23,33,43]]],[[[1,2,3,4],[12,23,33,43]],[[13,2,33,43],[31,23,33,43]]]])

In [35]:
arr4

array([[[[ 1,  2,  3,  4],
         [12, 23, 33, 43]],

        [[13,  2, 33, 43],
         [31, 23, 33, 43]]],


       [[[ 1,  2,  3,  4],
         [12, 23, 33, 43]],

        [[13,  2, 33, 43],
         [31, 23, 33, 43]]]])

In [32]:
arr4.ndim

4

In [36]:
arr4.shape

(2, 2, 2, 4)

In [37]:
arr3

array([[[ 1,  2,  3,  4],
        [12, 23, 33, 43]],

       [[13,  2, 33, 43],
        [31, 23, 33, 43]]])

In [39]:
arr3=arr3.flatten() # to convert multidimention to single dimention 

In [40]:
arr3

array([ 1,  2,  3,  4, 12, 23, 33, 43, 13,  2, 33, 43, 31, 23, 33, 43])

In [59]:
arr3.ndim

3

In [60]:
arr3

array([[[ 1,  2,  3,  4],
        [12, 23, 33, 43]],

       [[13,  2, 33, 43],
        [31, 23, 33, 43]]])

In [61]:
arr3.shape

(2, 2, 4)

In [63]:
arr3=arr3.flatten()

In [64]:
arr3

array([ 1,  2,  3,  4, 12, 23, 33, 43, 13,  2, 33, 43, 31, 23, 33, 43])

In [65]:
arr3=arr3.reshape(2,2,4)

In [67]:
arr3.size

16

In [68]:
arr3

array([[[ 1,  2,  3,  4],
        [12, 23, 33, 43]],

       [[13,  2, 33, 43],
        [31, 23, 33, 43]]])

In [70]:
arr3=arr3.reshape(4,4)

In [71]:
arr3.ndim

2

In [73]:
arr3

array([[ 1,  2,  3,  4],
       [12, 23, 33, 43],
       [13,  2, 33, 43],
       [31, 23, 33, 43]])

In [77]:
arr3.reshape(2,2,4)

array([[[ 1,  2,  3,  4],
        [12, 23, 33, 43]],

       [[13,  2, 33, 43],
        [31, 23, 33, 43]]])

# Linspace

In [94]:
larr=np.linspace(0,10,6)#min,max, no of elemnts with eual spacing

In [95]:
larr

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [99]:
np.linspace(4,10,5)

array([ 4. ,  5.5,  7. ,  8.5, 10. ])

# arange

In [105]:
np.arange(0,10,2.1)# min,max,stepsize whic accepts float

array([0. , 2.1, 4.2, 6.3, 8.4])

# random

In [118]:
np.random.rand(3,2)

array([[0.96411934, 0.16890999],
       [0.62989878, 0.19477253],
       [0.98196488, 0.76908363]])

In [120]:
np.random.random_integers(0,10,15)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 10 + 1) instead
  """Entry point for launching an IPython kernel.


array([3, 6, 9, 8, 8, 3, 5, 6, 9, 1, 5, 4, 1, 6, 4])

In [122]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [123]:
arr3

array([[ 1,  2,  3,  4],
       [12, 23, 33, 43],
       [13,  2, 33, 43],
       [31, 23, 33, 43]])

In [124]:
arr3.T # Transpose row to columns

array([[ 1, 12, 13, 31],
       [ 2, 23,  2, 23],
       [ 3, 33, 33, 33],
       [ 4, 43, 43, 43]])

In [125]:
np.transpose(arr3)

array([[ 1, 12, 13, 31],
       [ 2, 23,  2, 23],
       [ 3, 33, 33, 33],
       [ 4, 43, 43, 43]])

In [126]:
arr3

array([[ 1,  2,  3,  4],
       [12, 23, 33, 43],
       [13,  2, 33, 43],
       [31, 23, 33, 43]])

In [149]:
arr4=np.array([[1],[2],[3],[4]])

In [150]:
np.concatenate((arr3,arr4),axis=1)#axis=0 row, axis =1 column

array([[ 1,  2,  3,  4,  1],
       [12, 23, 33, 43,  2],
       [13,  2, 33, 43,  3],
       [31, 23, 33, 43,  4]])

In [152]:
arr4=np.array([[1,2,3,4]])

In [153]:
arr4

array([[1, 2, 3, 4]])

In [154]:
np.concatenate((arr3,arr4),axis=0)#axis=0 row, axis =1 column

array([[ 1,  2,  3,  4],
       [12, 23, 33, 43],
       [13,  2, 33, 43],
       [31, 23, 33, 43],
       [ 1,  2,  3,  4]])

In [155]:
arr3

array([[ 1,  2,  3,  4],
       [12, 23, 33, 43],
       [13,  2, 33, 43],
       [31, 23, 33, 43]])

In [157]:
arr3.dtype

dtype('int32')

In [159]:
arr3.astype(str)#convert one for to other format

array([['1', '2', '3', '4'],
       ['12', '23', '33', '43'],
       ['13', '2', '33', '43'],
       ['31', '23', '33', '43']], dtype='<U11')

In [26]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6,]])

In [27]:
x

array([[1, 2],
       [3, 4]])

In [28]:
y

array([[5, 6]])

In [29]:
x*y

array([[ 5, 12],
       [15, 24]])

In [30]:
np.save('my_array', x)

In [31]:
np.load("my_array.npy")

array([[1, 2],
       [3, 4]])

In [32]:
np.savetxt("myarray.txt", x, delimiter=" ")

In [39]:
np.loadtxt("myarray.txt",dtype='str')

array(['hi', 'hello'], dtype='<U5')